name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: clean and package code
      run: mvn clean package
    - name: Docker Build
      run: mvn package docker:build
